# Generated by Django 5.2.6 on 2025-10-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sepatu', 'Sepatu'), ('deker', 'Deker'), ('bola', 'Bola'), ('jersey', 'Jersey'), ('glove', 'Glove'), ('kaosKaki', 'KaosKaki')], default='update', max_length=20),
        ),
    ]
